algo = input('Digite algo: ')
print('O valor digitado foi {}' .format(algo))
print('O valor é do tipo {}' .format(type(algo)))
print('É espaço ?: {}' .format(algo.isspace()))
print('É númeco ?: {}' .format(algo.isnumeric()))
print('É alfabético ?: {}' .format(algo.isalpha()))
print('É alfanúmerico ?: {}' .format(algo.isalnum()))
print('Está em maiúscula ?: {}' .format(algo.isupper()))
print('Está em minuscula ?: {}' .format(algo.islower()))
print('Está capitalizada ?: {}' .format(algo.istitle()))
