texto = ' Desafio 022 '
print(' {:*^30}'. format(texto))
nome = str(input('Digite o nome completo : ')).strip()
print('O nome digitado foi : ', nome)
print('Em maiúsculo : ', nome.upper())
print('Em minusculo :', nome.lower())
print('tamanho com espaço : ', len(nome))
print('tamanho sem espaço : ', len(nome) - nome.count(' '))
primeiro = nome.split()
print('O primeiro nome tem {} letras' .format(len(primeiro[0])))